/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.io.FileReader;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class generadorCitas extends javax.swing.JFrame {
    private final generarCita file;
    public static String dirArchivo;   
    
    /**
     * Creates new form generadorCitas
     */
    public generadorCitas() {
        initComponents();
        
        setLocationRelativeTo(null);
        setResizable(false);
        txtDescripcionCita.setLineWrap(true);
        file = new generarCita( this.txtNombreEstudiante, this.txtFechaCita, this.txtHoraCita, this.txtDescripcionCita );
        setTitle("Generador de Citas");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        lblNombreEstudiante = new javax.swing.JLabel();
        lblFechaCita = new javax.swing.JLabel();
        lblHoraCita = new javax.swing.JLabel();
        btnEnviarCita = new javax.swing.JButton();
        lblDescripcionCita = new javax.swing.JLabel();
        txtNombreEstudiante = new javax.swing.JTextField();
        txtHoraCita = new javax.swing.JTextField();
        txtFechaCita = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();
        btnModificarCitas = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcionCita = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombreEstudiante.setText("Nombre Estudiante:");

        lblFechaCita.setText("Fecha para Cita:");

        lblHoraCita.setText("Hora para Cita:");

        btnEnviarCita.setText("Enviar");
        btnEnviarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarCitaActionPerformed(evt);
            }
        });

        lblDescripcionCita.setText("Descripcion:");

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnModificarCitas.setText("Modificar");
        btnModificarCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarCitasActionPerformed(evt);
            }
        });

        txtDescripcionCita.setColumns(20);
        txtDescripcionCita.setRows(5);
        jScrollPane2.setViewportView(txtDescripcionCita);

        jMenu1.setText("Citas");

        jMenuItem1.setText("Abrir Citas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreEstudiante)
                    .addComponent(lblDescripcionCita)
                    .addComponent(lblHoraCita)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnEnviarCita)
                        .addComponent(lblFechaCita)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(btnModificarCitas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                        .addComponent(btnAtras)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtFechaCita)
                                .addComponent(txtHoraCita, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                                .addComponent(txtNombreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreEstudiante)
                    .addComponent(txtNombreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaCita)
                    .addComponent(txtFechaCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoraCita)
                    .addComponent(txtHoraCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(lblDescripcionCita))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviarCita)
                    .addComponent(btnAtras)
                    .addComponent(btnModificarCitas))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarCitaActionPerformed
        // TODO add your handling code here:
        String datos = this.txtNombreEstudiante.getText() + "," + this.txtFechaCita.getText() + "," + this.txtHoraCita.getText() + "," + this.txtDescripcionCita.getText();
        file.Actualizar(datos);
        this.setTitle("" + file.getFileName() + "");
        
        
    }//GEN-LAST:event_btnEnviarCitaActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        entornoEstudiante obj= new entornoEstudiante();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        file.Abrir();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnModificarCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarCitasActionPerformed
        // TODO add your handling code here:
        String editarNombre = txtNombreEstudiante.getText();
        String editarHora = txtHoraCita.getText();
        String editarFecha = txtFechaCita.getText();
        String searchDescripcion = txtDescripcionCita.getText();
        
        //Un nuevo Arreglo temporal para albergar los campos de la ventana
        ArrayList<String> tempArray = new ArrayList<>();
        //Lectura del archivo
        try{
            //Se evalua las excepciónes
            try(FileReader fr = new FileReader(dirArchivo)){
                //Un lector del archivo directo
                Scanner reader = new Scanner(fr);
                //Es el que recorre las líneas del archivo para que luego se guarden dentro del Array
                String line;
                //Para guardar los datos anteriores
                String [] lineArray;
                
                //Ciclo para verificar el archivo y que sea diferente hasta que no encuentre más líneas dentro del archivo
                while((line = reader.nextLine()) != null){
                    //Está poniendo comas en cada terminación de un campo
                    lineArray = line.split(",");
                    //Se compara para proceder a editar los parámetros de las ventanas
                    if(lineArray[3].equals(searchDescripcion)){
                        tempArray.add(
                        lineArray[0] + "," +
                        editarFecha  + "," +
                        editarHora +","+
                        lineArray[3]);
   
                    }else{
                        tempArray.add(line);
                        
                    }
                }
                fr.close();
            //Segunda ecxepción por si no hay nigún campo en el archivo con los parámetros a evaluar
            }catch(Exception e){   
            }
        //Prinera excepción para si no encuentra la dirección del archivo
        }catch(Exception e){
        }
        
        try{
            try(PrintWriter pr= new PrintWriter(dirArchivo)){
                for (String srt : tempArray) {
                    pr.println(srt);
                }
                pr.close();
            }catch(Exception e){
            }
            
        }catch(Exception e){ 
        }
    }//GEN-LAST:event_btnModificarCitasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(generadorCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(generadorCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(generadorCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(generadorCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new generadorCitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnEnviarCita;
    private javax.swing.JButton btnModificarCitas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblDescripcionCita;
    private javax.swing.JLabel lblFechaCita;
    private javax.swing.JLabel lblHoraCita;
    private javax.swing.JLabel lblNombreEstudiante;
    private javax.swing.JTextArea txtDescripcionCita;
    private javax.swing.JTextField txtFechaCita;
    private javax.swing.JTextField txtHoraCita;
    private javax.swing.JTextField txtNombreEstudiante;
    // End of variables declaration//GEN-END:variables
}
